// COMMON - 서버,클라 공용
// SERVER - 서버에서만 사용
// CLIENT - 클라에서만 사용

COMMON	"character.txt.txt"
COMMON	"character-etc.txt.txt"
COMMON	"character-school.txt.txt"
COMMON	"etc.txt.txt"
COMMON	"propCtrl.txt.txt"
COMMON	"propItem.txt.txt"
COMMON	"propItemEtc.txt.txt"
COMMON	"propKarma.txt.txt"
COMMON	"propMotion.txt.txt"
COMMON	"propMover.txt.txt"
COMMON	"propQuest.txt.txt"
COMMON	"propQuest-DungeonandPK.txt.txt"
COMMON	"propQuest-RequestBox2.txt.txt"
COMMON	"propQuest-RequestBox.txt.txt"
COMMON	"propQuest-Scenario.txt.txt"
COMMON	"propSkill.txt.txt"
COMMON	"propTroupeSkill.txt.txt"
COMMON	"honorList.txt.txt"
COMMON	"textClient.txt.txt"
COMMON	"textEmotion.txt.txt"
COMMON	"world.txt.txt"
COMMON	"lordskill.txt.txt"

CLIENT	"propMapComboBoxData.txt.txt"
CLIENT	"resData.txt.txt"
CLIENT	"Client\treeHelp.txt.txt"
CLIENT	"Client\tip.txt.txt"
CLIENT	"Client\PatchClient.txt.txt"
CLIENT	"Client\InstantHelp.txt.txt"
CLIENT	"Client\help.txt.txt"
CLIENT	"Client\Guide.txt.txt"
CLIENT	"Client\tutorial.txt.txt"
CLIENT	"Client\faq.txt.txt"

CLIENT	"World\WdVolcane\WdVolcane.txt.txt"
CLIENT	"World\WdMadrigal\wdMadrigal.txt.txt"
CLIENT	"World\WdKebaras\WdKebaras.txt.txt"
CLIENT	"World\WdGuildWar\WdGuildWar.txt.txt"
CLIENT	"World\WdEvent01\WdEvent01.txt.txt"
CLIENT	"World\DuMuscle\DuMuscle.txt.txt"
CLIENT	"World\DuKrr\DuKrr.txt.txt"
CLIENT	"World\DuFlMas\DuFlMas.txt.txt"
CLIENT	"World\DuDaDk\DuDaDk.txt.txt"
CLIENT	"World\DuBear\DuBear.txt.txt"
CLIENT	"World\DuSaTemple\DuSaTemple.txt.txt"
CLIENT	"World\DuSaTempleBoss\DuSaTempleBoss.txt.txt"
CLIENT	"World\WdVolcane\WdVolcane.txt.txt"
CLIENT	"World\WdVolcaneRed\WdVolcaneRed.txt.txt"
CLIENT	"World\WdVolcaneYellow\WdVolcaneYellow.txt.txt"
CLIENT	"World\WdArena\WdArena.txt.txt"
CLIENT	"World\WdHeaven01\wdheaven01.txt.txt"
CLIENT	"World\WdHeaven02\wdheaven02.txt.txt"
CLIENT	"World\WdHeaven03\wdheaven03.txt.txt"
CLIENT	"World\WdHeaven04\wdheaven04.txt.txt"
CLIENT	"World\WdHeaven05\wdheaven05.txt.txt"
CLIENT	"World\WdHeaven06\wdheaven06.txt.txt"
CLIENT	"World\WdHeaven06_1\wdheaven06_1.txt.txt"
CLIENT	"World\WdCisland\WdCisland.txt.txt"
CLIENT	"World\DuOminous\duominous.txt.txt"
CLIENT	"World\DuOminous_1\duominous_1.txt.txt"
CLIENT	"World\WdGuildhousesmall\WdGuildhousesmall.txt.txt"		// 소형 길드하우스
CLIENT	"World\WdGuildhousemiddle\WdGuildhousemiddle.txt.txt"	// 중형 길드하우스
CLIENT	"World\WdGuildhouselarge\WdGuildhouselarge.txt.txt"		// 대형 길드하우스
CLIENT	"World\DuDreadfulCave\DuDreadfulCave.txt.txt"			// 추가 인던(드래드풀 케이브)
CLIENT	"World\DuRustia\DuRustia.txt.txt"						// 추가 인던(러스티아 일반)
CLIENT	"World\DuRustia_1\DuRustia_1.txt.txt"					// 추가 인던(러스티아 마스터)
CLIENT	"World\WdRartesia\WdRartesia.txt.txt"			// 16차 라르테시아
CLIENT	"World\DuBehamah\DuBehamah.txt.txt"				// 16차 베히모스 신전
CLIENT	"World\DuKalgas\DuKalgas.txt.txt"				// 17차 칼가스
CLIENT	"World\WdColosseum\WdColosseum.txt.txt"			// 17차 콜로세움
CLIENT	"World\DuUpresia\DuUpresia.txt.txt"
CLIENT	"World\DuUpresia_1\DuUpresia_1.txt.txt"
CLIENT	"World\DuSanpres\DuSanpres.txt.txt"
CLIENT	"World\DuSanpres_1\DuSanpres_1.txt.txt"
CLIENT	"World\DuHerneos\DuHerneos.txt.txt"
CLIENT	"World\DuHerneos_1\DuHerneos_1.txt.txt"
CLIENT	"World\WdFwc\WdFwc.txt.txt"
CLIENT	"World\WdMarket\WdMarket.txt.txt"
CLIENT	"World\WdDarkRartesia\WdDarkRartesia.txt.txt"
CLIENT	"World\DuContaminatedTrails\DuContaminatedTrails.txt.txt"