// COMMON - 서버,클라 공용
// SERVER - 서버에서만 사용
// CLIENT - 클라에서만 사용

COMMON	"define.h"
COMMON	"defineAttribute.h"
COMMON	"defineEvent.h"
COMMON	"defineHonor.h"
COMMON	"defineItem.h"
COMMON	"defineItemGrade.h"
COMMON	"defineItemkind.h"
COMMON	"defineItemType.h"
COMMON	"defineJob.h"
COMMON	"definelordskill.h"
COMMON	"defineNeuz.h"
COMMON	"defineObj.h"
COMMON	"definequest.h"
COMMON	"defineSkill.h"
COMMON	"defineSound.h"
COMMON	"defineText.h"
COMMON	"defineWorld.h"
COMMON	"lang.h"

SERVER	"defineEventArena.h"


CLIENT	"ContinentDef.h"
CLIENT	"defineMapComboBoxData.h"
CLIENT	"ResData.h"
CLIENT	"WndStyle.h"
