// 첫숫자는 키, 중복금지

1
{
	title( "IDS_TEXTCLIENT_INC_003470" );
	type1( TYPE1_WEAPON );
}

2
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003477" );
	type2( TYPE2_WEAPON_ONESWORD );
}

3
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003478" );
	type2( TYPE2_WEAPON_TWOSWORD );
}

4
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003479" );
	type2( TYPE2_WEAPON_ONEAXE );
}


5
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003480" );
	type2( TYPE2_WEAPON_TWOAXE );
}


6
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003481" );
	type2( TYPE2_WEAPON_KNUCKLE  );
}


7
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003482" );
	type2( TYPE2_WEAPON_STICK );
}

8
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003483" );
	type2( TYPE2_WEAPON_BOW );
}


9
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003484" );
	type2( TYPE2_WEAPON_STAFF );
}


10
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003485" );
	type2( TYPE2_WEAPON_YOYO );
}

11
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003486" );
	type2( TYPE2_WEAPON_WAND );
}


12
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003487" );
	type2( TYPE2_ARMOR_FORCEZEM );
}


13
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003488" );
	type2( TYPE2_ARMOR_MAGICBOOK );
}

14
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003489" );
	type2( TYPE2_WEAPON_ALLEXCEPTION );
}


15
{
	title( "IDS_TEXTCLIENT_INC_003471" );
	type1( TYPE1_ARMOR );
}


16
{
	parent( 15 );
	title( "IDS_TEXTCLIENT_INC_003490" );
	type2( TYPE2_ARMOR_HELMET);
}

17
{
	parent( 15 );
	title( "IDS_TEXTCLIENT_INC_003491" );
	type2( TYPE2_ARMOR_SUIT );
}

18
{
	parent( 15 );
	title( "IDS_TEXTCLIENT_INC_003492" );
	type2( TYPE2_ARMOR_GUNTLET );
}


19
{
	parent( 15 );
	title( "IDS_TEXTCLIENT_INC_003493" );
	type2( TYPE2_ARMOR_BOOTS );
}


20
{
	parent( 15 );
	title( "IDS_TEXTCLIENT_INC_003494" );
	type2( TYPE2_ARMOR_SHIELD );
}



21
{
	title( "IDS_TEXTCLIENT_INC_003472" );
	type1( TYPE1_ACCESSORY );
}


22
{
	parent( 21 );
	title( "IDS_TEXTCLIENT_INC_003495" );
	type2( TYPE2_ACCESSORY_RING );
}


23
{
	parent( 21 );
	title( "IDS_TEXTCLIENT_INC_003496" );
	type2( TYPE2_ACCESSORY_EARRING );
}

24
{
	parent( 21 );
	title( "IDS_TEXTCLIENT_INC_003497" );
	type2( TYPE2_ACCESSORY_NECKLACE );
}


25
{
	title( "IDS_TEXTCLIENT_INC_003473" );
	type1( TYPE1_MATERIAL );
}

26
{
	parent( 25 );
	title( "IDS_TEXTCLIENT_INC_003498" );
	type2( TYPE2_MATERIAL_EXCEPTION );
}


27
{
	title( "IDS_TEXTCLIENT_INC_003474" );
	type1( TYPE1_CONSUME );
}

28
{
	parent( 27 );
	title( "IDS_TEXTCLIENT_INC_003499" );
	type2( TYPE2_CONSUME_POTION );
}


29
{
	parent( 27 );
	title( "IDS_TEXTCLIENT_INC_003500" );
	type2( TYPE2_CONSUME_SCROLL );
}

30
{
	parent( 27 );
	title( "IDS_TEXTCLIENT_INC_003501" );
	type2( TYPE2_CONSUME_POSTER );
}


31
{
	parent( 27 );
	title( "IDS_TEXTCLIENT_INC_003502" );
	type2( TYPE2_CONSUME_EXCEPTION );
}

32
{
	title( "IDS_TEXTCLIENT_INC_003476" );
	type1( TYPE1_COSTUME );
}

33
{
	parent( 32);
	title( "IDS_TEXTCLIENT_INC_003504" );
	type2( TYPE2_COSTUME_MASK );
}
34
{
	parent( 32);
	title( "IDS_TEXTCLIENT_INC_003505" );
	type2( TYPE2_COSTUME_CLOAK );
}

35
{
	parent( 32);
	title( "IDS_TEXTCLIENT_INC_003506" );
	type2( TYPE2_COSTUME_HAT );
}

36
{
	parent( 32);
	title( "IDS_TEXTCLIENT_INC_003507" );
	type2( TYPE2_COSTUME_CLOTH );
}

37
{
	parent( 32);
	title( "IDS_TEXTCLIENT_INC_003508" );
	type2( TYPE2_COSTUME_GLOVE );
}

38
{
	parent( 32);
	title( "IDS_TEXTCLIENT_INC_003509" );
	type2( TYPE2_COSTUME_SHOES );
}

39
{
	title( "IDS_TEXTCLIENT_INC_003731" );
	type1( TYPE1_PET );
}
40
{
	parent( 39);
	title( "IDS_TEXTCLIENT_INC_003733" );
	type2( TYPE2_PET_EGG );
}
41
{
	parent( 39);
	title( "IDS_TEXTCLIENT_INC_003732" );
	type2( TYPE2_PET_PICKUP );
}
42
{
	parent( 39);
	title( "IDS_TEXTCLIENT_INC_003734" );
	type2( TYPE2_PET_REAR );
}
43
{
	parent( 39);
	title( "IDS_TEXTCLIENT_INC_003735" );
	type2( TYPE2_PET_BUFF );
}
44
{
	title( "IDS_TEXTCLIENT_INC_003475" );
	type1( TYPE1_ALLEXCEPTION );
}

45
{
	parent( 44);
	title( "IDS_TEXTCLIENT_INC_003503" );
	type2( TYPE2_ALLEXCEPTION_ALLEXCEPTION );
}