MCD_WORLD
{
	SetCategory( MCC_MAP_CATEGORY );
	SetTitle( IDS_PROPMAP_TXT_000001 );
}

MCD_REGION
{
	SetCategory( MCC_MAP_CATEGORY );
	SetTitle( IDS_PROPMAP_TXT_000002 );
}

MCD_TOWN
{
	SetCategory( MCC_MAP_CATEGORY );
	SetTitle( IDS_PROPMAP_TXT_000003 );
}

MCD_DUNGEON
{
	SetCategory( MCC_MAP_CATEGORY );
	SetTitle( IDS_PROPMAP_TXT_000242 );
}

MCD_CASHAREA
{
	SetCategory( MCC_MAP_CATEGORY );
	SetTitle( IDS_PROPMAP_TXT_000257 );
}

MCD_MADRIGAL
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000004 );
	SetPictureFile( "WORLD_Flyff.dds" );
	SetRealPositionRect( 195, 1376, 11938, 10429);
	SetLocationID( CONT_NODATA );
	SetParentID( MCD_WORLD );
}

MCD_DARKON_12
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000005 );
	SetPictureFile( "WORLD_Darkon12.dds" );
	SetRealPositionRect( 2355, 2019, 7187, 5814 );
	SetMonsterInformationFile( "texMapMonster_Darkon12.inc" );
	SetLocationID( CONT_DARKON12 );
	SetParentID( MCD_REGION );
}

MCD_DARKON_3
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000006 );
	SetPictureFile( "WORLD_Darkon3.dds" );
	SetRealPositionRect( 985, 1621, 5754, 5149 );
	SetMonsterInformationFile( "texMapMonster_Darkon3.inc" );
	SetLocationID( CONT_DARKON3 );
	SetParentID( MCD_REGION );
}

MCD_RICIS
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000007 );
	SetPictureFile( "WORLD_Ricis.dds" );
	SetRealPositionRect( 8080, 3200, 10280, 5000 );
	SetMonsterInformationFile( "texMapMonster_Ricis.inc" );
	SetLocationID( CONT_RICIS );
	SetParentID( MCD_REGION );
}

MCD_SAINT_MORNING
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000008 );
	SetPictureFile( "WORLD_Saint.dds" );
	SetRealPositionRect( 6854, 1580, 10600, 4430 );
	SetMonsterInformationFile( "texMapMonster_Saint.inc" );
	SetLocationID( CONT_SAINTMORNING );
	SetParentID( MCD_REGION );
}

MCD_FLARIS
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000009 );
	SetPictureFile( "WORLD_Flaris.dds" );
	SetRealPositionRect( 5500, 2540, 9200, 5130 );
	SetMonsterInformationFile( "texMapMonster_Flaris.inc" );
	SetLocationID( CONT_FLARIS );
	SetParentID( MCD_REGION );
}

MCD_HARMONIN
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000010 );
	SetPictureFile( "WORLD_harmonin.dds" );
	SetRealPositionRect( 4795, 4587, 8391, 7236 );
	SetMonsterInformationFile( "texMapMonster_Harmonin.inc" );
	SetLocationID( CONT_HARMONIN );
	SetParentID( MCD_REGION );
}

MCD_ESTIA
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000011 );
	SetPictureFile( "WORLD_Estia.dds" );
	SetRealPositionRect( 5150, 5573, 9890, 9158 );
	SetMonsterInformationFile( "texMapMonster_Estia.inc" );
	SetLocationID( CONT_ESTIA );
	SetParentID( MCD_REGION );
}

MCD_KAILLUN
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000015 );
	SetPictureFile( "WORLD_kaillun.dds" );
	SetRealPositionRect( 6130, 8103, 8848, 10129 );
	SetMonsterInformationFile( "texMapMonster_Kaillun.inc" );
	SetLocationID( CONT_KAILLUN );
	SetParentID( MCD_REGION );
}

MCD_BAHARA
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000241 );
	SetPictureFile( "WORLD_bahara.dds" );
	SetRealPositionRect( 4264, 7851, 7020, 9860 );
	SetMonsterInformationFile( "texMapMonster_Bahara.inc" );
	SetLocationID( CONT_BAHARA );
	SetParentID( MCD_REGION );
}



MCD_FLARINE
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000012 );
	SetPictureFile( "Town_Flarine.dds" );	
	SetRealPositionRect( 6847, 3110, 7258, 3421 ); 
	SetLocationID( TOWN_FLARINENOSPLE );
	SetParentID( MCD_TOWN );
}

MCD_SAINCITY
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000013 );
	SetPictureFile( "Town_Saincity.dds" );
	SetRealPositionRect( 8013, 3514, 8879, 4144 );
	SetLocationID( TOWN_SAINCITY );
	SetParentID( MCD_TOWN );
}

MCD_DARKEN
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000014 );
	SetPictureFile( "Town_Darken.dds" );
	SetRealPositionRect( 3622, 4280, 4110, 4620 );
	SetLocationID( TOWN_DARKEN );
	SetParentID( MCD_TOWN );
}

MCD_ELLIUN
{
	SetCategory( MCC_MAP_NAME );
	SetTitle( IDS_PROPMAP_TXT_000016 );
	SetPictureFile( "Town_Elliun.dds" );
	SetRealPositionRect( 7080, 8989, 7523, 9325);
	SetLocationID( TOWN_ELIUN );
	SetParentID( MCD_TOWN );
}

//던전 지도
MCD_OMINOUS01
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Ominous.dds" );
	SetTitle( IDS_PROPMAP_TXT_000243 );	
	SetRealPositionRect(896, 1272, 1442, 1686);
	SetLocationID( DUNGEON_OMINOUS01 );
	SetParentID( MCD_DUNGEON );

}

MCD_OMINOUS02
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Ominous01.dds" );
	SetTitle( IDS_PROPMAP_TXT_000244 );	
	SetRealPositionRect( 896, 1272, 1442, 1686);
	SetLocationID( DUNGEON_OMINOUS02 );
	SetParentID( MCD_DUNGEON );
}

MCD_BEHAMAH
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Behamah.dds" );
	SetTitle( IDS_PROPMAP_TXT_000245 );	
	SetRealPositionRect( -136, 283, 1549, 1546 );
	SetLocationID( DUNGEON_BEHEMOTH );
	SetParentID( MCD_DUNGEON );
}

MCD_DREADFULCAVE
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Dreadfulcave.dds" );
	SetTitle( IDS_PROPMAP_TXT_000246 );
	SetRealPositionRect( 185, -15, 2304, 1550 );
	SetLocationID( DUNGEON_DREADFULCAVE );
	SetParentID( MCD_DUNGEON );
}

MCD_RUSTIA_1
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Rustia_1.dds" );
	SetTitle( IDS_PROPMAP_TXT_000261 );	
	SetRealPositionRect(148, 454, 2048, 1892);
	SetLocationID( DUNGEON_RUSTIA_1 );
	SetParentID( MCD_DUNGEON );

}

MCD_RUSTIA_2
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Rustia_2.dds" );
	SetTitle( IDS_PROPMAP_TXT_000262 );	
	SetRealPositionRect(148, 454, 2048, 1892);
	SetLocationID( DUNGEON_RUSTIA_2 );
	SetParentID( MCD_DUNGEON );

}

MCD_KALGAS
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Kalgas.dds" );
	SetTitle( IDS_PROPMAP_TXT_000264 );	
	SetRealPositionRect(72, -506, 3124, 1835);
	SetLocationID( DUNGEON_KALGAS );
	SetParentID( MCD_DUNGEON );

}

MCD_MASDUNGEON
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Masdungeon.dds" );
	SetTitle( IDS_PROPMAP_TXT_000263 );	
	SetRealPositionRect(381, 347, 2028, 1503);
	SetLocationID( DUNGEON_MASDUNGEON );
	SetParentID( MCD_DUNGEON );

}

MCD_DEKANES
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Dekanes.dds" );
	SetTitle( IDS_PROPMAP_TXT_000265 );	
	SetRealPositionRect(532, 205, 2343, 1489);
	SetLocationID( DUNGEON_DEKANES );
	SetParentID( MCD_DUNGEON );

}

MCD_IBLESS
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Ibless.dds" );
	SetTitle( IDS_PROPMAP_TXT_000266 );	
	SetRealPositionRect(342, 378, 1844, 1465);
	SetLocationID( DUNGEON_IBLESS );
	SetParentID( MCD_DUNGEON );

}

MCD_RARTESIA
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "WORLD_Rartesia.dds" );
	SetTitle( IDS_PROPMAP_TXT_000260 );
	SetRealPositionRect( 129, 500, 2850, 2600 );
	SetLocationID( CASHAREA_RARTESIA );
	SetParentID( MCD_CASHAREA );
}

MCD_SANPRES
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Sanpres.dds" );
	SetTitle( IDS_PROPMAP_TXT_000267 );
	SetRealPositionRect( -60, 35, 2618, 1908 );
	SetLocationID( DUNGEON_SANPRES );
	SetParentID( MCD_DUNGEON );
}

MCD_SANPRES_1
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Sanpres_1.dds" );
	SetTitle( IDS_PROPMAP_TXT_000268 );
	SetRealPositionRect( -60, 35, 2618, 1908 );
	SetLocationID( DUNGEON_SANPRES_1 );
	SetParentID( MCD_DUNGEON );
}

MCD_UPRESIA
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Upresia.dds" );
	SetTitle( IDS_PROPMAP_TXT_000269 );
	SetRealPositionRect( 524, 349, 2961, 2158 );
	SetLocationID( DUNGEON_UPRESIA );
	SetParentID( MCD_DUNGEON );
}

MCD_UPRESIA_1
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Upresia_1.dds" );
	SetTitle( IDS_PROPMAP_TXT_000270 );
	SetRealPositionRect( 524, 349, 2961, 2158 );
	SetLocationID( DUNGEON_UPRESIA_1 );
	SetParentID( MCD_DUNGEON );
}

MCD_VOLCANE
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_Volcane.dds" );
	SetTitle( IDS_PROPMAP_TXT_000273 );
	SetRealPositionRect(-34,229, 2051, 1808 );
	SetLocationID( DUNGEON_VOLCANE );
	SetParentID( MCD_DUNGEON );
}

MCD_HERNEOS
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Herneos.dds" );
	SetTitle( IDS_PROPMAP_TXT_000271 );
	SetRealPositionRect( 33, 52, 2958, 2203 );
	SetLocationID( DUNGEON_HERNEOS );
	SetParentID( MCD_DUNGEON );
}

MCD_HERNEOS_1
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Herneos_1.dds" );
	SetTitle( IDS_PROPMAP_TXT_000272 );
	SetRealPositionRect( 33, 52, 2958, 2203 );
	SetLocationID( DUNGEON_HERNEOS_1 );
	SetParentID( MCD_DUNGEON );
}

MCD_WdHeaven01
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_WdHeaven01.dds" );
	SetTitle( IDS_PROPMAP_TXT_000274 );
	SetRealPositionRect( -78, -52, 584, 554 );
	SetLocationID( DUNGEON_WdHeaven01);
	SetParentID( MCD_DUNGEON );
}

MCD_WdHeaven02
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_WdHeaven02.dds" );
	SetTitle( IDS_PROPMAP_TXT_000275 );
	SetRealPositionRect( -107, -72, 609, 564 );
	SetLocationID( DUNGEON_WdHeaven02);
	SetParentID( MCD_DUNGEON );
}

MCD_WdHeaven03
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_WdHeaven03.dds" );
	SetTitle( IDS_PROPMAP_TXT_000276 );
	SetRealPositionRect( -157, -152, 664, 644 );
	SetLocationID( DUNGEON_WdHeaven03);
	SetParentID( MCD_DUNGEON );
}

MCD_WdHeaven04
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_WdHeaven04.dds" );
	SetTitle( IDS_PROPMAP_TXT_000277 );
	SetRealPositionRect( -145, -145, 654, 603 );
	SetLocationID( DUNGEON_WdHeaven04);
	SetParentID( MCD_DUNGEON );
}

MCD_WdHeaven05
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_WdHeaven05.dds" );
	SetTitle( IDS_PROPMAP_TXT_000278 );
	SetRealPositionRect( -230, -165, 640, 609 );
	SetLocationID( DUNGEON_WdHeaven05 );
	SetParentID( MCD_DUNGEON );
}


MCD_DuContaminatedTrails
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "Dungeon_ContaminatedTrails.dds" );
	SetTitle( IDS_PROPMAP_TXT_000282 );
	SetRealPositionRect( -820, -23, 3400, 3032 );
	SetLocationID( DUNGEON_ContaminatedTrails );
	SetParentID( MCD_DUNGEON );
}


//유료 지역

MCD_CORALICELAND
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "DUNGEON_Cisland.dds" );
	SetTitle( IDS_PROPMAP_TXT_000258 );
	SetRealPositionRect( -14, 65, 3195, 2482 );
	SetLocationID( CASHAREA_CORALICELAND );
	SetParentID( MCD_CASHAREA );
}

MCD_ASRIA
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "WORLD_Azria.dds" );
	SetTitle( IDS_PROPMAP_TXT_000259 );
	SetRealPositionRect( 7, 48, 2769, 2403 );
	SetLocationID( CASHAREA_ASRIA );
	SetParentID( MCD_CASHAREA );
}
MCD_DARKRARTESIA
{
	SetCategory( MCC_MAP_NAME );
	SetPictureFile( "WORLD_darkRartesia.dds" );
	SetTitle( IDS_PROPMAP_TXT_000280 );
	SetRealPositionRect( 129, 500, 2850, 2600 );
	SetLocationID( CASHAREA_DARKRARTESIA );
	SetParentID( MCD_CASHAREA );
}

// 플라리스 마을
MCD_FLARINENOSPLE_NPC1
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000017 );	 
	SetNPCPosition( 6960, 3339 );
	SetParentID( MCD_FLARINE );
}

/*
MCD_FLARINENOSPLE_NPC2
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000018 );	 
	SetNPCPosition( 6958, 3349 );
	SetParentID( MCD_FLARINE );
}
*/

MCD_FLARINENOSPLE_NPC3
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000019 );	 
	SetNPCPosition( 6929, 3328 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC4
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000020 );	 
	SetNPCPosition( 6986, 3335 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC5
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000021 );	 
	SetNPCPosition( 6986, 3326 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC6
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000022 );	 
	SetNPCPosition( 6982, 3306 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC7
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000023 );	 
	SetNPCPosition( 6961, 3349 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC8
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000024 );
	 
	SetNPCPosition( 6930, 3324 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC9
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000025 );
	 
	SetNPCPosition( 6982, 3351 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC10
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000026 );	 
	SetNPCPosition( 6986, 3331 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC11
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000027 );	 
	SetNPCPosition( 6986, 3322 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC12
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000028 );	 
	SetNPCPosition( 6981, 3305 );
	SetParentID( MCD_FLARINE );
}


MCD_FLARINENOSPLE_NPC14
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000030 );	 
	SetNPCPosition( 6947, 3274 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC15
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000031 );	 
	SetNPCPosition( 6932, 3259 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC16
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000032 );	 
	SetNPCPosition( 6927, 3236 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC17
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000033 );	 
	SetNPCPosition( 6926, 3229 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC18
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000034 );	 
	SetNPCPosition( 6930, 3225 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC19
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000035 );	 
	SetNPCPosition( 6961, 3211 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC20
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000036 );	 
	SetNPCPosition( 6989, 3231 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC21
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000037 );	 
	SetNPCPosition( 6975, 3266 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC22
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000038 );	 
	SetNPCPosition( 6958, 3238 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC23
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000039 );	 
	SetNPCPosition( 6999, 3203 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC24
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000040 );	 
	SetNPCPosition( 6954, 3273 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC25
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000041 );	 
	SetNPCPosition( 6926, 3232 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC26
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000042 );	 
	SetNPCPosition( 6927, 3229 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC27
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000043 );	 
	SetNPCPosition( 6958, 3211 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC28
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000044 );	 
	SetNPCPosition( 6960, 3204 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC29
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000045 );	 
	SetNPCPosition( 6989, 3256 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC30
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000046 );	 
	SetNPCPosition( 6937, 3243 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC31
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000047 );	 
	SetNPCPosition( 6960, 3227 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC32
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000048 );	 
	SetNPCPosition( 6960, 3266 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC33
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000049 );	 
	SetNPCPosition( 6953, 3213 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC34
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000050 );	 
	SetNPCPosition( 6970, 3215 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC35
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000051 );	 
	SetNPCPosition( 7041, 3243 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC36
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000052 );	 
	SetNPCPosition( 7130, 3257 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC37
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000053 );	 
	SetNPCPosition( 7179, 3217 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC38
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000054 );	 
	SetNPCPosition( 7169, 3208 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC39
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000055 );	 
	SetNPCPosition( 7129, 3252 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC40
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000056 );	 
	SetNPCPosition( 7169, 3271 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC41
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000057 );	 
	SetNPCPosition( 7172, 3212 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC42
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000058 );	 
	SetNPCPosition( 7159, 3221 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC43
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000059 );	 
	SetNPCPosition( 7155, 3248 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC44
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000060 );	 
	SetNPCPosition( 7156, 3250 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC45
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000061 );	 
	SetNPCPosition( 7202, 3229 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC46
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000062 ); 	 
	SetNPCPosition( 7204, 3229 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC47
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000063 );	 
	SetNPCPosition( 7204, 3226 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC48
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000064 );	 
	SetNPCPosition( 7153, 3244 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC49
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000065 );	 
	SetNPCPosition( 7152, 3242 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC50
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000066 );	 
	SetNPCPosition( 7203,  3231 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC51
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000067 );	 
	SetNPCPosition( 7204, 3228 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC52
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000068 );	 
	SetNPCPosition( 7219,  3190 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC53
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000108 );	 
	SetNPCPosition( 7169,  3242 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC54
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000121 );	 
	SetNPCPosition( 7168,  3242 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC55
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000119 );	 
	SetNPCPosition( 6932,  3327 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC56
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000254 );	 
	SetNPCPosition( 6932,  3327 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC57
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000255 );	 
	SetNPCPosition( 7166,  3239 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC58
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000256  );	 
	SetNPCPosition( 7165,  3238 );
	SetParentID( MCD_FLARINE );
}

MCD_FLARINENOSPLE_NPC59
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000279  );	 
	SetNPCPosition( 7157,  3236 );
	SetParentID( MCD_FLARINE );
}



MCD_SAINCITY_NPC1
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000070 );	 
	SetNPCPosition( 8315, 3728 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC2
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000071 );	 
	SetNPCPosition( 8360, 3750 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC3
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000072 );	 
	SetNPCPosition( 8369, 3675 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC4
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000073 );	 
	SetNPCPosition( 8375, 3673 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC5
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000074 );	 
	SetNPCPosition( 8359, 3640 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC6
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000075 );	 
	SetNPCPosition( 8449, 3638 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC7
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000076 );	 
	SetNPCPosition( 8478, 3634 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC8
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000077 );	 
	SetNPCPosition( 8410, 3680 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC9
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000078 );	 
	SetNPCPosition( 8462, 3709 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC10
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000079 );	 
	SetNPCPosition( 8532, 3607 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC11
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000080 );	 
	SetNPCPosition( 8483, 3810 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC12
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000081 );	 
	SetNPCPosition( 8636, 3738 );
	SetParentID( MCD_SAINT_MORNING );
}

MCD_SAINCITY_NPC13
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000082 );	 
	SetNPCPosition( 8445, 3576 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC14
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000083 );	 
	SetNPCPosition( 8341, 3750 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC15
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000084 );	 
	SetNPCPosition( 8335, 3713 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC16
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000085 );	 
	SetNPCPosition( 8372, 3671 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC17
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000086 );	 
	SetNPCPosition( 8374, 3659 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC18
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000087 );	 
	SetNPCPosition( 8437, 3615 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC19
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000088 );	 
	SetNPCPosition( 8465, 3622 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC20
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000089 );	 
	SetNPCPosition( 8464, 3652 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC21
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000090 );	 
	SetNPCPosition( 8480, 3660 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC22
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000091 );	 
	SetNPCPosition( 8536, 3643 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC23
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000092 );	 
	SetNPCPosition( 8481, 3810 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC24
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000093 );	 
	SetNPCPosition( 8443, 3602 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC25
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000094 );	 
	SetNPCPosition( 8439, 3547 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC26
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000095 );	 
	SetNPCPosition( 8353, 3983 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC27
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000096 );	 
	SetNPCPosition( 8484, 3601 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC28
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000097 );	 
	SetNPCPosition( 8463, 3600 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC29
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000098 );	 
	SetNPCPosition( 8414, 3974 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC30
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000099 );	 
	SetNPCPosition( 8412, 3974 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC31
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000100 );	 
	SetNPCPosition( 8383, 4085 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC32
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000101 );	 
	SetNPCPosition( 8385, 3653 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC33
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000102 );	 
	SetNPCPosition( 8396, 3654 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC34
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000103 );	 
	SetNPCPosition( 8397, 3657 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC35
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000104 );	 
	SetNPCPosition( 8387, 3651 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC36
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000105 );	 
	SetNPCPosition( 8395, 3655 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC37
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000106 );	 
	SetNPCPosition( 8403, 3657 );
	SetParentID( MCD_SAINCITY );
}

MCD_SAINCITY_NPC38
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000030 );	 
	SetNPCPosition( 8464, 3644 );
	SetParentID( MCD_SAINCITY );
}


MCD_DARKEN_NPC2
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000109 );	 
	SetNPCPosition( 3831, 4355 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC3
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000110 );	 
	SetNPCPosition( 3742, 4413 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC4
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000111 );	 
	SetNPCPosition( 3743, 4424 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC5
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000112 );	 
	SetNPCPosition( 3784, 4490 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC6
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000113 );	 
	SetNPCPosition( 3795, 4498 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC7
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000114 );	 
	SetNPCPosition( 3781, 4485 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC8
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000115 );	 
	SetNPCPosition( 3787, 4481 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC9
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000116 );	 
	SetNPCPosition( 3833, 4480 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC10
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000117 );	 
	SetNPCPosition( 3826, 4459 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC11
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000118 );	 
	SetNPCPosition( 3831, 4457 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC13
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000120 );	 
	SetNPCPosition( 3801, 4448 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC15
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000122 );	 
	SetNPCPosition( 3909, 4375 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC16
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000123 );	 
	SetNPCPosition( 3748, 4412 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC17
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000124 );	 
	SetNPCPosition( 3742, 4419 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC18
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000125 );	 
	SetNPCPosition( 3733, 4526 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC19
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000126 );	 
	SetNPCPosition( 3790, 4492 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC20
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000127 );	 
	SetNPCPosition( 3798, 4490 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC21
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000128 );	 
	SetNPCPosition( 3796, 4487 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC22
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000129 );	 
	SetNPCPosition( 3793, 4482 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC23
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000130 );	 
	SetNPCPosition( 3824, 4462 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC24
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000131 );	 
	SetNPCPosition( 3829, 4457 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC25
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000132 );	 
	SetNPCPosition( 3846, 4442 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC26
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000133 );	 
	SetNPCPosition( 3841, 4422 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC27
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000134 );	 
	SetNPCPosition( 3804, 4456 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC28
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000135 );	 
	SetNPCPosition( 3835, 4455 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC29
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000136 );	 
	SetNPCPosition( 3794, 4444 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC30
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000137 );	 
	SetNPCPosition( 3850, 4659 );
	SetParentID( MCD_DARKON_12 );
}

MCD_DARKEN_NPC31
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000138 );	 
	SetNPCPosition( 3827, 4548 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC32
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000139 );	 
	SetNPCPosition( 3879, 4457 );
	SetParentID( MCD_DARKEN );
}

MCD_DARKEN_NPC33
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000140 );	 
	SetNPCPosition( 3240, 3417 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKEN_NPC34
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000141 );	 
	SetNPCPosition( 3209, 3436 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKEN_NPC35
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000142 );	 
	SetNPCPosition( 3170, 3644 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKEN_NPC36
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000143 );	 
	SetNPCPosition( 2992, 4063 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKEN_NPC37
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000144 );	 
	SetNPCPosition( 3237, 3421 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKEN_NPC38
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000145 );	 
	SetNPCPosition( 3202, 3437 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKEN_NPC39
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000146 );	 
	SetNPCPosition( 3959, 3509  );
	SetParentID( MCD_DARKON_3 );
}

MCD_ELIUN_NPC1
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000154 );	 
	SetNPCPosition( 7249, 9138  );
	SetParentID( MCD_ELLIUN );
}

MCD_ELIUN_NPC2
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000155 );	 
	SetNPCPosition( 7252, 9134  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC3
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000156 );	 
	SetNPCPosition( 7248, 9141  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC4
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000157 );	 
	SetNPCPosition( 7250, 9181  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC5
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000158 );	 
	SetNPCPosition( 7346, 9146  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC6
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000159 );	 
	SetNPCPosition( 7332, 9125  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC7
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000160 );	 
	SetNPCPosition( 7312, 9113  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC8
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000161 );	 
	SetNPCPosition( 7290, 9112  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC9
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000162 );	 
	SetNPCPosition( 7287, 9112  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC10
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000163 );	 
	SetNPCPosition( 7281, 9260  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC11
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000164 );	 
	SetNPCPosition( 7362, 9231  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC12
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000165 );	 
	SetNPCPosition( 7388, 9152  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC13
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000166 );	 
	SetNPCPosition( 7361, 9030  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC14
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000167 );	 
	SetNPCPosition( 7368, 9033  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC15
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000168 );	 
	SetNPCPosition( 7364, 9023  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC16
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000169 );	 
	SetNPCPosition( 7371, 9027  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC17
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000170 );	 
	SetNPCPosition( 7262, 9200  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC18
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000171 );	 
	SetNPCPosition( 7281, 9211  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC19
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000172 );	 
	SetNPCPosition( 7305, 9213  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC20
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000173 );	 
	SetNPCPosition( 7340, 9186  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC21
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000174 );	 
	SetNPCPosition( 7192, 9135  );
	SetParentID( MCD_ELLIUN );
}

/*
MCD_ELIUN_NPC22
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000175 );	 
	SetNPCPosition( 7187, 9143  );
	SetParentID( MCD_ELLIUN );
}
*/

MCD_ELIUN_NPC23
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000176 );	 
	SetNPCPosition( 7233, 9296  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC24
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000177 );	 
	SetNPCPosition( 7226, 9293  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC25
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000178 );	 
	SetNPCPosition( 7229, 9302  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC26
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000179 );	 
	SetNPCPosition( 7222, 9298  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC27
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000180 );	 
	SetNPCPosition( 7400, 9182  );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC28
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000181 );	 
	SetNPCPosition( 7375, 9093 );
	SetParentID( MCD_ELLIUN );
}


MCD_ELIUN_NPC29
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000182 );	 
	SetNPCPosition( 7240, 9093  );
	SetParentID( MCD_ELLIUN );
}

MCD_ELIUN_NPC30
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000253 );	 
	SetNPCPosition( 7380, 9068  );
	SetParentID( MCD_ELLIUN );
}

MCD_ELIUN_NPC31
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000217 );	 
	SetNPCPosition( 7351, 9174  );
	SetParentID( MCD_ELLIUN );
}

MCD_ELIUN_NPC32
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000283 );	 
	SetNPCPosition( 7351, 9174  );
	SetParentID( MCD_ELLIUN );
}



MCD_MCD_FLARIS_NPC53
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000183 );	 
	SetNPCPosition( 7741, 4074  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC54
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000184 );	 
	SetNPCPosition( 7185, 4090  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC55
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000185 );	 
	SetNPCPosition( 6943, 3101  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC56
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000186 );	 
	SetNPCPosition( 6836, 3133  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC57
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000187 );	 
	SetNPCPosition( 7677, 4253  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC58
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000188 );	 
	SetNPCPosition( 7639, 4255  );
	SetParentID( MCD_FLARIS );
}


MCD_MCD_FLARIS_NPC59
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000189 );	 
	SetNPCPosition( 7637, 4228  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC60
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000190 );	 
	SetNPCPosition( 7656, 4191  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC61
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000191 );	 
	SetNPCPosition( 7694, 4226  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC62
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000192 );	 
	SetNPCPosition( 7678, 4252  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC63
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000193 );	 
	SetNPCPosition( 7636, 4229  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC64
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000194 );	 
	SetNPCPosition( 7658, 4190  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC65
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000195 );	 
	SetNPCPosition( 7694, 4228  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC66
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000196 );	 
	SetNPCPosition( 6994, 3897  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC67
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000197 );	 
	SetNPCPosition( 6991, 3891  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC68
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000198 );	 
	SetNPCPosition( 6998, 3896  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC69
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000199 );	 
	SetNPCPosition( 7001, 3895  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC70
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000200 );	 
	SetNPCPosition( 7036, 3729  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC71
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000201 );	 
	SetNPCPosition( 6551, 3619  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC72
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000202 );	 
	SetNPCPosition( 7454, 3671  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC73
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000203 );	 
	SetNPCPosition( 7214, 3673  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC74
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000204 );	 
	SetNPCPosition( 6690, 3618  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC75
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000205 );	 
	SetNPCPosition( 6705, 3327  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC76
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000206 );	 
	SetNPCPosition( 6703, 3328  );
	SetParentID( MCD_FLARIS );
}

MCD_MCD_FLARIS_NPC77
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000050 );	 
	SetNPCPosition( 7338, 3931  );
	SetParentID( MCD_FLARIS );
}
MCD_MCD_FLARIS_NPC78
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000281 );	 
	SetNPCPosition( 7160, 3236  );
	SetParentID( MCD_FLARINE );
}

MCD_SAINT_MORNING_NPC38
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000207 );	 
	SetNPCPosition( 8637, 3569  );
	SetParentID( MCD_SAINT_MORNING );
}


MCD_SAINT_MORNING_NPC39
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000208 );	 
	SetNPCPosition( 7941, 2405  );
	SetParentID( MCD_SAINT_MORNING );
}

MCD_SAINT_MORNING_NPC40
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000209 );	 
	SetNPCPosition( 8199, 2805  );
	SetParentID( MCD_SAINT_MORNING );
}

MCD_SAINT_MORNING_NPC41
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000210 );	 
	SetNPCPosition( 8247, 2526  );
	SetParentID( MCD_SAINT_MORNING );
}

MCD_SAINT_MORNING_NPC43
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000050 );	 
	SetNPCPosition( 8280, 2811  );
	SetParentID( MCD_SAINT_MORNING );
}

MCD_SAINT_MORNING_NPC44
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000252 );	 
	SetNPCPosition( 8529, 3475  );
	SetParentID( MCD_SAINT_MORNING );
}

MCD_DARKON_12_NPC40
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000211 );	 
	SetNPCPosition( 5852, 4317  );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC41
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000212 );	 
	SetNPCPosition( 5541, 4352  );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC42
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000213 );	 
	SetNPCPosition( 6131, 4165  );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC43
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000214 );	 
	SetNPCPosition( 5535, 3461  );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC44
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000215 );	 
	SetNPCPosition( 5371, 3991  );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC45
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000216 );	 
	SetNPCPosition( 5481, 4363 );
	SetParentID( MCD_DARKON_12 );
}

MCD_DARKON_3_NPC46
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000217 );	 
	SetNPCPosition( 3343, 1858 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC47
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000218 );	 
	SetNPCPosition( 3947, 2748 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC48
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000219 );	 
	SetNPCPosition( 3007, 3967 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC49
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000220 );	 
	SetNPCPosition( 3012, 2931 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC50
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000221 );	 
	SetNPCPosition( 2788, 2885 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC51
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000222 );	 
	SetNPCPosition( 3526, 2792 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC52
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000223 );	 
	SetNPCPosition( 3320, 2067 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC53
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000224 );	 
	SetNPCPosition( 3361, 2085 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC54
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000225 );	 
	SetNPCPosition( 3343, 2090 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC55
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000226 );	 
	SetNPCPosition( 3366, 2045 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC56
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000227 );	 
	SetNPCPosition( 3337, 2042 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC57
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000228 );	 
	SetNPCPosition( 3327, 2085 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC58
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000229 );	 
	SetNPCPosition( 3371, 2060 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC59
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000230 );	 
	SetNPCPosition( 3351, 2040 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC60
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000231 );	 
	SetNPCPosition( 3524, 3547 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC61
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000232 );	 
	SetNPCPosition( 2522, 4599 );
	SetParentID( MCD_DARKON_3 );
}

MCD_DARKON_3_NPC62
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000233 );	 
	SetNPCPosition( 3273, 4250 );
	SetParentID( MCD_DARKON_3 );
}


MCD_SAINT_MORNING_NPC42
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000234 );	 
	SetNPCPosition( 9558, 4018 );
	SetParentID( MCD_RICIS );
}

MCD_HARMONIN01
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000148 );	 
	SetNPCPosition( 5959, 5406 );
	SetParentID( MCD_HARMONIN );
}

MCD_HARMONIN02
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000149 );	 
	SetNPCPosition( 5937, 5431 );
	SetParentID( MCD_HARMONIN );
}


MCD_HARMONIN03
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000150 );	 
	SetNPCPosition( 6025, 5346 );
	SetParentID( MCD_HARMONIN );
}


MCD_HARMONIN04
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000151 );	 
	SetNPCPosition( 5962, 5387 );
	SetParentID( MCD_HARMONIN );
}

MCD_HARMONIN05
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000152 );	 
	SetNPCPosition( 5987, 5457 );
	SetParentID( MCD_HARMONIN );
}


MCD_DARKON_12_NPC63
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000235 );	 
	SetNPCPosition( 5600, 3765 );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC64
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000236  );	 
	SetNPCPosition( 5560, 3907 );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC65
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000237  );	 
	SetNPCPosition( 5569, 3900 );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC66
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000238  );	 
	SetNPCPosition( 5571, 3899 );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC67
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000239 );	 
	SetNPCPosition( 5579, 3902 );
	SetParentID( MCD_DARKON_12 );
}


MCD_DARKON_12_NPC68
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000240 );	 
	SetNPCPosition( 5576, 3898 );
	SetParentID( MCD_DARKON_12 );
}


MCD_BAHARA_NPC1
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000247 );	 
	SetNPCPosition( 6007, 9260 );
	SetParentID( MCD_BAHARA );
}

MCD_BAHARA_NPC2
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000248 );	 
	SetNPCPosition( 6009, 9248 );
	SetParentID( MCD_BAHARA );
}

MCD_BAHARA_NPC3
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000249 );	 
	SetNPCPosition( 6070, 9234 );
	SetParentID( MCD_BAHARA );
}
	
MCD_BAHARA_NPC4
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000250 );	 
	SetNPCPosition( 6064, 9190 );
	SetParentID( MCD_BAHARA );
}

MCD_BAHARA_NPC5
{
	SetCategory( MCC_NPC_NAME );
	SetTitle( IDS_PROPMAP_TXT_000251 );	 
	SetNPCPosition( 5758, 8165 );
	SetParentID( MCD_BAHARA );
}
