//프리프조각 UI관련 아이템 트리

1
{
	title( "IDS_TEXTCLIENT_INC_003470" );
	type1( TYPE1_WEAPON );
}

2
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003477" );
	type2( TYPE2_WEAPON_ONESWORD );
}

3
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003478" );
	type2( TYPE2_WEAPON_TWOSWORD );
}

4
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003479" );
	type2( TYPE2_WEAPON_ONEAXE );
}

5
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003480" );
	type2( TYPE2_WEAPON_TWOAXE );
}

6
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003481" );
	type2( TYPE2_WEAPON_KNUCKLE  );
}

7
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003482" );
	type2( TYPE2_WEAPON_STICK );
}

8
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003483" );
	type2( TYPE2_WEAPON_BOW );
}

9
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003484" );
	type2( TYPE2_WEAPON_STAFF );
}

10
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003485" );
	type2( TYPE2_WEAPON_YOYO );
}

11
{
	parent( 1 );
	title( "IDS_TEXTCLIENT_INC_003486" );
	type2( TYPE2_WEAPON_WAND );
}

12
{
	title( "IDS_TEXTCLIENT_INC_003471" );
	type1( TYPE1_ARMOR );
}

13
{
	parent( 12 );
	title( "IDS_TEXTCLIENT_INC_003490" );
	type2( TYPE2_ARMOR_HELMET);
}

14
{
	parent( 12 );
	title( "IDS_TEXTCLIENT_INC_003491" );
	type2( TYPE2_ARMOR_SUIT );
}

15
{
	parent( 12 );
	title( "IDS_TEXTCLIENT_INC_003492" );
	type2( TYPE2_ARMOR_GUNTLET );
}

16
{
	parent( 12 );
	title( "IDS_TEXTCLIENT_INC_003493" );
	type2( TYPE2_ARMOR_BOOTS );
}

17
{
	parent( 12 );
	title( "IDS_TEXTCLIENT_INC_003494" );
	type2( TYPE2_ARMOR_SHIELD );
}

18
{
	parent( 12 );
	title( "IDS_TEXTCLIENT_INC_003487" );
	type2( TYPE2_ARMOR_FORCEZEM );
}

19
{
	parent( 12 );
	title( "IDS_TEXTCLIENT_INC_003488" );
	type2( TYPE2_ARMOR_MAGICBOOK );
}

20
{
	title( "IDS_TEXTCLIENT_INC_003472" );
	type1( TYPE1_ACCESSORY );
}

21
{
	parent( 20 );
	title( "IDS_TEXTCLIENT_INC_003496" );
	type2( TYPE2_ACCESSORY_EARRING );
}

22
{
	parent( 20 );
	title( "IDS_TEXTCLIENT_INC_003497" );
	type2( TYPE2_ACCESSORY_NECKLACE );
}

23
{
	parent( 20 );
	title( "IDS_TEXTCLIENT_INC_003495" );
	type2( TYPE2_ACCESSORY_RING );
}

24
{
	title( "IDS_TEXTCLIENT_INC_003474" );
	type1( TYPE1_CONSUME );
}

25
{
	parent( 24 );
	title( "IDS_TEXTCLIENT_INC_003502" );
	type2( TYPE2_CONSUME_EXCEPTION );	
}