MI_RANGDA01
{
	nInterval	3600	// 리스폰 주기(단위: 초)
	nReplace	3600	// 위치 이동 주기(단위: 초)
	bActiveAttack	0	// 선공 여부 : 비선공 0
	vRangda		// 리스폰 좌표
	{
		WI_WORLD_MADRIGAL	4609.0   60.0   4409.0
		WI_WORLD_MADRIGAL	4390.0   20.0   3998.0
		WI_WORLD_MADRIGAL	4496.0   60.0   3846.0
	}
}

MI_RANGDA02
{
	nInterval	3600	// 리스폰 주기(단위: 초)
	nReplace	3600	// 위치 이동 주기(단위: 초)
	bActiveAttack	0	// 선공 여부 : 비선공 0
	vRangda		// 리스폰 좌표
	{
		WI_WORLD_MADRIGAL	2587.0  52.0  3603.0
		WI_WORLD_MADRIGAL	3589.0  36.0  3849.0
		WI_WORLD_MADRIGAL	4080.0  30.0  3711.0
	}
}

MI_RANGDA03
{
	nInterval	3600	// 리스폰 주기(단위: 초)
	nReplace	3600	// 위치 이동 주기(단위: 초)
	bActiveAttack	0	// 선공 여부 : 비선공 0
	vRangda		// 리스폰 좌표
	{
		WI_WORLD_MADRIGAL	3187.0  36.0  3192.0
		WI_WORLD_MADRIGAL	3512.0  117.0 2190.0 
		WI_WORLD_MADRIGAL	2805.0  109.0 2336.0 
	}
}

MI_RANGDA04
{
	nInterval	3600	// 리스폰 주기(단위: 초)
	nReplace	3600	// 위치 이동 주기(단위: 초)
	bActiveAttack	0	// 선공 여부 : 비선공 0
	vRangda		// 리스폰 좌표
	{
		WI_DUNGEON_VOLCANE	 601.0   89.0   1509.0
		WI_DUNGEON_VOLCANE	 509.0   87.0    597.0
		WI_DUNGEON_VOLCANE	1498.0   88.0   1524.0
	}
}